[project]
name = "bibel-korpus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dhlab>=2.42.1",
    "jupyter>=1.1.1",
]
